/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.brunner.service.sales;

import java.util.HashMap;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.annotation.PostConstruct;

import org.apache.ibatis.session.SqlSession;
import org.springframework.stereotype.Component;

import com.brunner.service.SVC_AuthorityGroup.Constants_AuthorityGroup;
import com.brunner.service.SVC_AuthorityGroup.Messages_AuthorityGroup;
import com.brunner.service.sales.dao.TB_CUS_PRODUCT_SALES;
import com.brunner.service.util.Constants;
import com.brunner.service.util.ExceptionUtil;
import com.brunner.service.util.MapUtil;
import com.brunner.service.util.Messages;
import com.google.gson.JsonArray;
import com.google.gson.JsonNull;
import com.google.gson.JsonObject;

import mw.utility.BrunnerLogger;

@Component
public class SVC_ProductSales {
	private final String CLASS = this.getClass().getName();
	private final Logger logger = BrunnerLogger.getLogger(CLASS);

	@PostConstruct
	public void init() {
		System.out.println(String.format("init bean [%s]", this.getClass().getName()));
	}	
	
	public JsonObject TXN_ProductSales_registerProductSales(
			SqlSession session,
			JsonObject request) {
		
		final String METHOD = new Exception().getStackTrace()[0].getMethodName();
		
		JsonObject reply = null;
		String resultCode = Constants_ProductSales.resultCode_systemException;
		String resultMessage = Constants_ProductSales.emptyString;
		String txnId = request.get(Constants.msgFieldName_inputData).getAsJsonObject().get(Constants.msgFieldName_txnId).getAsString();
		
   		logger.log(Level.INFO, String.format(Messages_AuthorityGroup.msg_startService, 
   				txnId, 
   				CLASS, 
   				METHOD));   			

   		int nEffected = 0;
   		
   		try {
   			String salesSerialNo = MapUtil.getNullableString(request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject(), "salesSerialNo");
	   		if(salesSerialNo == null || salesSerialNo.isEmpty() == true) {
	   			// 신규 등록
	   			nEffected = TB_CUS_PRODUCT_SALES.insert_01(
	   					session,
	   					txnId,
	    				request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("systemCode").getAsString(), 
	    				request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("userId").getAsString(),
	    				MapUtil.getNullableString(request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject(), "salesSerialNo"),
	    				request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("salesDate").getAsString(),
	    				request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("customerId").getAsString(),
	    				request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("productName").getAsString(),
	    				request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("productUnit").getAsString(),
	    				request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("unitPrice").getAsInt(),
	    				request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("salesCount").getAsFloat(),
	    				request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("salesAmount").getAsFloat(),
	    				request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("receivedAmount").getAsFloat(),
	    				request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("salesComment").getAsString()
	    				);
	
				if(nEffected == 1) {
	    			resultCode = Constants_ProductSales.resultCode_success;
	    			resultMessage = String.format(Messages_ProductSales.msg_successfullyFinished, CLASS, METHOD);
				} else if(nEffected == 0) {
					// 오류: 변경행 없음  			resultCode = Constants_ProductSales.resultCode_failToUpdateData;
	    			resultMessage = String.format(Messages_ProductSales.msg_failToUpdateData);
				} else {
					// 오류: 여러건 변경
	    			resultCode = Constants_ProductSales.resultCode_failToUpdateData;
	    			resultMessage = String.format(Messages_ProductSales.msg_affectedDataMoreThanOneRow);
				}
	   		} else {
	   			// 기존 업데이트
	   			
	    		List<HashMap<String, Object>> rows = TB_CUS_PRODUCT_SALES.select_02(
	    				session,
	    				txnId,
	    				request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("systemCode").getAsString(), 
	    				request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("userId").getAsString(),
	    				request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("salesSerialNo").getAsString()
	    				);
				
	   			if(rows.size() > 0) {
		   			nEffected = TB_CUS_PRODUCT_SALES.update_01(
		   					session,
		   					txnId,
		    				request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("systemCode").getAsString(), 
		    				request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("userId").getAsString(),
		    				request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("salesSerialNo").getAsString(),
		    				request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("salesCount").getAsFloat(),
		    				request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("salesAmount").getAsFloat(),
		    				request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("receivedAmount").getAsFloat(),
		    				request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("salesComment").getAsString()
		    				);
		
					if(nEffected == 1) {
		    			resultCode = Constants_ProductSales.resultCode_success;
		    			resultMessage = String.format(Messages_ProductSales.msg_successfullyFinished, CLASS, METHOD);
					} else if(nEffected == 0) {
		    			resultCode = Constants_ProductSales.resultCode_failToUpdateData;
		    			resultMessage = String.format(Messages_ProductSales.msg_failToUpdateData);
					} else {
						// 오류: 여러건 변경
		    			resultCode = Constants_ProductSales.resultCode_failToUpdateData;
		    			resultMessage = String.format(Messages_ProductSales.msg_affectedDataMoreThanOneRow);
					}
	   			} else {
	   				// 오류:기존 매출이 없음
	    			resultCode = Constants_ProductSales.resultCode_noDataFound;
	    			resultMessage = String.format(Messages_ProductSales.msg_noSuchSalesInfo, salesSerialNo);
	   			}
	   		}
   		}
   		catch (Exception e) {
			resultCode = Constants_ProductSales.resultCode_systemException;
			resultMessage = ExceptionUtil.getFullMessage(e);
			logger.log(Level.SEVERE, resultMessage);
		}
		finally {
			reply = new JsonObject();
			reply.addProperty(Constants.msgFieldName_txnId,	txnId);
			reply.addProperty(Constants.msgFieldName_resultCode, resultCode);
			reply.addProperty(Constants.msgFieldName_resultMessage, resultMessage);

			logger.log(Level.INFO, String.format(Messages_AuthorityGroup.msg_endService, 
	   				txnId, 
	   				CLASS, 
	   				METHOD));
		}
		return reply;
    }
	
	public JsonObject TXN_ProductSales_unregisterProductSales(
			SqlSession session,
			JsonObject request) {
		
		final String METHOD = new Exception().getStackTrace()[0].getMethodName();
		
		JsonObject reply = null;
		String resultCode = Constants_ProductSales.resultCode_systemException;
		String resultMessage = Constants_ProductSales.emptyString;
		String txnId = request.get(Constants.msgFieldName_inputData).getAsJsonObject().get(Constants.msgFieldName_txnId).getAsString();
		
		
   		logger.log(Level.INFO, String.format(Messages_AuthorityGroup.msg_startService, 
   				txnId, 
   				CLASS, 
   				METHOD));   	
   		
   		int nEffected = 0;
   		
   		try {
   			String salesSerialNo = MapUtil.getNullableString(request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject(), "salesSerialNo");
   			
    		List<HashMap<String, Object>> rows = TB_CUS_PRODUCT_SALES.select_02(
    				session,
    				txnId,
    				request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("systemCode").getAsString(), 
    				request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("userId").getAsString(),
    				request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("salesSerialNo").getAsString()
    				);
			
   			if(rows.size() > 0) {
	   			nEffected = TB_CUS_PRODUCT_SALES.update_02(
	   					session,
	   					txnId,
	    				request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("systemCode").getAsString(), 
	    				request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("userId").getAsString(),
	    				request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("salesSerialNo").getAsString()
	    				);
	
				if(nEffected == 1) {
	    			resultCode = Constants_ProductSales.resultCode_success;
	    			resultMessage = String.format(Messages_ProductSales.msg_successfullyFinished, CLASS, METHOD);
				} else if(nEffected == 0) {
	    			resultCode = Constants_ProductSales.resultCode_failToUpdateData;
	    			resultMessage = String.format(Messages_ProductSales.msg_failToUpdateData);
				} else {
	    			resultCode = Constants_ProductSales.resultCode_failToUpdateData;
	    			resultMessage = String.format(Messages_ProductSales.msg_affectedDataMoreThanOneRow);
				}
   			} else {
   				// 오류:기존 매출이 없음
    			resultCode = Constants_ProductSales.resultCode_noDataFound;
    			resultMessage = String.format(Messages_ProductSales.msg_noSuchSalesInfo, salesSerialNo);
   			}
		} catch (Exception e) {
			resultCode = Constants_ProductSales.resultCode_systemException;
			resultMessage = ExceptionUtil.getFullMessage(e);
			logger.log(Level.SEVERE, resultMessage);
		}
		finally {
			reply = new JsonObject();
			reply.addProperty(Constants.msgFieldName_txnId, txnId);
			reply.addProperty(Constants.msgFieldName_resultCode, resultCode);
			reply.addProperty(Constants.msgFieldName_resultMessage, resultMessage);

			logger.log(Level.INFO, String.format(Messages_AuthorityGroup.msg_endService, 
	   				txnId, 
	   				CLASS, 
	   				METHOD));
		}
		return reply;
    }	

	public JsonObject TXN_ProductSales_viewProductSalesList(
			SqlSession session,
			JsonObject request) {
		
		final String METHOD = new Exception().getStackTrace()[0].getMethodName();
		
		JsonObject reply = null;
		String resultCode = Constants_ProductSales.resultCode_systemException;
		String resultMessage = Constants_ProductSales.emptyString;		
		String txnId = request.get(Constants.msgFieldName_inputData).getAsJsonObject().get(Constants.msgFieldName_txnId).getAsString();
			
   		logger.log(Level.INFO, String.format(Messages_AuthorityGroup.msg_startService, 
   				txnId, 
   				CLASS, 
   				METHOD));   	

   		List<HashMap<String, Object>> rows = null;
   		
   		try {
   			if(request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().has("customerId") == false ||
   			   request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("customerId").equals(JsonNull.INSTANCE) ||
   			request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("customerId").getAsString().equals("")){
  	    		rows = TB_CUS_PRODUCT_SALES.select_01(
   	    				session,
   	    				txnId,
   	    				request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("systemCode").getAsString(), 
   	    				request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("userId").getAsString(),
   	    				request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("fromDate").getAsString(),
   	    				request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("toDate").getAsString()
   	    				);   				
   			} 
   			else {
   				rows = TB_CUS_PRODUCT_SALES.select_03(
   	    				session,
   	    				txnId,
   	    				request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("systemCode").getAsString(), 
   	    				request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("userId").getAsString(),
   	    				request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("fromDate").getAsString(),
   	    				request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("toDate").getAsString(),
   	    				request.get(Constants_ProductSales.msgFieldName_inputData).getAsJsonObject().get("customerId").getAsString()
   	    				);
    			}
   			

    		JsonArray jProductList = new JsonArray();
    		for(int rowIndex = 0; rowIndex < rows.size(); rowIndex++) {
    			JsonObject jRow = new JsonObject();
    			HashMap<String, Object> row = rows.get(rowIndex);
    			jRow.addProperty("salesSerialNo", row.get("SALES_SERIAL_NO").toString());
       			jRow.addProperty("salesDate", MapUtil.getNullableString(row, "SALES_DATE"));
       		    jRow.addProperty("customerId", MapUtil.getNullableString(row, "CUSTOMER_ID"));
       		    jRow.addProperty("registerName", MapUtil.getNullableString(row, "REGISTER_NAME"));
       			jRow.addProperty("productName", MapUtil.getNullableString(row, "PRODUCT_NAME"));
    			jRow.addProperty("productUnit", MapUtil.getNullableString(row, "PRODUCT_UNIT"));
    			jRow.addProperty("unitPrice", MapUtil.getNullableString(row, "UNIT_PRICE").toString());
    			jRow.addProperty("salesCount", MapUtil.getNullableString(row, "SALES_COUNT"));
    			jRow.addProperty("salesAmount", MapUtil.getNullableString(row, "SALES_AMOUNT").toString());
    			jRow.addProperty("receivedAmount", MapUtil.getNullableString(row, "RECEIVED_AMOUNT").toString());
       			jRow.addProperty("salesComment", MapUtil.getNullableString(row, "SALES_COMMENT").toString());
       		    			
    			jProductList.add(jRow);
    		}

    		reply = new JsonObject();
    		reply.addProperty(Constants.msgFieldName_txnId, txnId);
			reply.add("productSalesList", jProductList);

    		resultCode = Constants_AuthorityGroup.resultCode_success;

    		reply.addProperty(Constants.msgFieldName_resultCode, resultCode);
			reply.addProperty(Constants.msgFieldName_resultMessage, resultMessage);
    		
		} catch (Exception e) {
			resultCode = Constants_ProductSales.resultCode_systemException;
			resultMessage = ExceptionUtil.getFullMessage(e);
			logger.log(Level.SEVERE, resultMessage);
		}
		finally {

			logger.log(Level.INFO, String.format(Messages_AuthorityGroup.msg_endService, 
	   				txnId, 
	   				CLASS, 
	   				METHOD));
		}
		return reply;
    }	
	
	class Constants_ProductSales extends Constants {
	}	

	static class Messages_ProductSales extends Messages {
		public static String msg_noSuchSalesInfo = "Product sales info [%s] not exist.";

	}	
}
